package com.immortalmc.adapter.command;

public enum ImmortalCommandAction {
    HEALTH,
    SPIRIT_ROOT,
    SPIRIT_ROOT_DETECTOR_CREATE,
    SPIRIT_ROOT_DETECTOR_LIST,
    SPIRIT_ROOT_DETECTOR_REMOVE,
    SPIRIT_ROOT_DETECTOR_SET,
    SPIRIT_ROOT_DETECTOR_RELOAD,
    NPC_DIALOGUE_SET,
    NPC_DIALOGUE_LIST,
    NPC_DIALOGUE_REMOVE,
    NPC_DIALOGUE_RELOAD,
    USAGE
}
