from typing import Protocol
from uuid import UUID

from immortal_mmo.player.models import Account, CurrentLifeQuestFacts, Life, SpiritRoot


class PlayerRepository(Protocol):
    async def upsert_account(self, minecraft_uuid: UUID, last_known_name: str) -> Account: ...

    async def lock_account(self, account_id: UUID) -> Account | None: ...

    async def get_current_life(self, account_id: UUID, *, for_update: bool) -> Life | None: ...

    async def get_lives(self, account_id: UUID) -> tuple[Life, ...]: ...

    async def insert_first_life(self, account_id: UUID) -> Life: ...

    async def get_spirit_root(self, life_id: UUID) -> SpiritRoot | None: ...

    async def insert_spirit_root(self, spirit_root: SpiritRoot) -> bool: ...

    async def increment_life_revision(self, life_id: UUID) -> int: ...

    async def get_current_life_facts(
        self,
        account_id: UUID,
        *,
        for_update: bool,
    ) -> CurrentLifeQuestFacts | None: ...
